require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetingsController do

  before (:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
    @meeting =  FactoryGirl.create(:meeting)
  end

  describe "GET new" do
    it "assigns a new meeting as @meeting" do
      get :new
      assigns(:meeting).should be_a_new(Meeting)
    end
  end

  describe "GET index" do
    it "assigns all meetings as @meetings" do
      #meeting = FactoryGirl.create(:meeting)
      get :index
      assigns(:meetings).should eq([@meeting])
    end
  end

  describe "GET show" do
    it "assigns the requested meeting as @meeting" do
      #meeting = FactoryGirl.create(:meeting)
      get :show, {:id => @meeting.to_param}
      assigns(:meeting).should eq(@meeting)
    end
  end


  describe "DELETE destroy" do
    it "destroys the requested meeting" do
      #meeting = FactoryGirl.create(:meeting)
      expect {
        delete :destroy, {:id => @meeting.to_param}
      }.to change(Meeting, :count).by(-1)
    end

    it "redirects to the meetings list" do
      #meeting = FactoryGirl.create(:meeting)
      delete :destroy, {:id => @meeting.to_param}
      response.should redirect_to(meetings_url)
    end
  end  

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Meeting" do
        attrs = FactoryGirl.attributes_for(:meeting2)
        expect {
          post :create, {:meeting => attrs}
        }.to change(Meeting, :count).by(1)
      end

      it "assigns a newly created meeting as @meeting" do
        attrs = FactoryGirl.attributes_for(:meeting2)
        post :create, {:meeting => attrs}
        assigns(:meeting).should be_a(Meeting)
        assigns(:meeting).should be_persisted
      end

      it "redirects to the created meeting" do
        attrs = FactoryGirl.attributes_for(:meeting2)
        post :create, {:meeting => attrs}
        response.should redirect_to(Meeting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meeting as @meeting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meeting.any_instance.stub(:save).and_return(false)
        post :create, {:meeting => {}}
        assigns(:meeting).should be_a_new(Meeting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meeting.any_instance.stub(:save).and_return(false)
        post :create, {:meeting => {}}
        response.should render_template("new")
      end
    end
  end

end
